version: '3.8'

services:
  typebot:
    image: typebot/typebot:latest
    environment:
      - DATABASE_URL=postgresql://typebot:typebot@db:5432/typebot
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_VIEWER_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: typebot
      POSTGRES_USER: typebot
      POSTGRES_PASSWORD: typebot
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - typebot
      - db
    environment:
      - DATABASE_URL=postgresql://typebot:typebot@db:5432/typebot
      - TYPEBOT_URL=http://typebot:3000

volumes:
  postgres-data: